model:
  model_path: meta-llama/Meta-Llama-3-8B

data:
  train_path: fineweb_100BT
  train_size: 1000000000000
  dataloader:
    type: native
    drop_last: true
  datasets_type: iterable
  data_type: plaintext
  max_seq_len: 8192
  text_keys: text

train:
  accelerator:
    ulysses_size: 1
    fsdp_config:
      fsdp_mode: fsdp2
      mixed_precision:
        enable: false
    offload:
      enable_activation: false
  gradient_checkpointing:
    enable: true
  global_batch_size: 512
  micro_batch_size: 1
  bsz_warmup_ratio: 0.007
  optimizer:
    type: adamw
    lr: 3.0e-4
    lr_warmup_ratio: 0.007
    lr_decay_style: constant
    lr_decay_ratio: 1.0
    weight_decay: 0.01
    max_grad_norm: 1.0
  init_device: meta
  enable_full_determinism: false
  empty_cache_steps: 500
  checkpoint:
    output_dir: llama3-8b
    manager: dcp
    save_steps: 100
    save_hf_weights: true
  wandb:
    project: Meta-Llama-3-8B
    name: Meta-Llama-3-8B-CT
