model:
  model_path: /PATH/TO/SEED-OSS

data:
  train_path: fineweb_100BT
  train_size: 1000000000000
  dataloader:
    type: native
    drop_last: true
  datasets_type: iterable
  data_type: plaintext
  max_seq_len: 4096
  text_keys: text

train:
  accelerator:
    fsdp_config:
      fsdp_mode: fsdp2
  init_device: meta
  global_batch_size: 512
  micro_batch_size: 1
  bsz_warmup_ratio: 0.007
  optimizer:
    lr: 3.0e-4
    lr_warmup_ratio: 0.007
    lr_decay_style: constant
    lr_decay_ratio: 1.0
    weight_decay: 0.01
    max_grad_norm: 1.0
  checkpoint:
    output_dir: seed_oss
    manager: dcp
  wandb:
    project: seed_oss
    name: seed_oss_sft
